"""
Certificate Generator Module for Induction App
Generates personalized PDF certificates for users who complete onboarding
"""

from fpdf import FPDF
import datetime
import os
import re
from modules.data_manager import get_user_profile, get_user_completion_status, load_data


def sanitize_text(text):
    """Remove emojis and non-latin characters from text for PDF compatibility."""
    if not text:
        return ""
    clean = re.sub(r'[^\x00-\x7F]+', '', str(text))
    return clean.strip()


class Certificate(FPDF):
    def __init__(self):
        super().__init__(orientation='L', format='A4')  # Landscape
        self.set_auto_page_break(auto=False)


def generate_certificate(user_name=None, user_email=None):
    """
    Generate a PDF certificate for a user who completed all guides.
    Returns the file path or None if failed.
    """
    # Get user info
    if not user_name:
        profile = get_user_profile()
        if profile:
            user_name = profile.get("name", "Employee")
            user_email = profile.get("email", "")
        else:
            return None
    
    # Verify completion
    status = get_user_completion_status()
    if not status.get("all_complete"):
        return None
    
    # Get completed guides
    completed_guides = [cat["name"] for cat in status.get("categories", []) if cat["guide_complete"]]
    
    pdf = Certificate()
    pdf.add_page()
    
    # --- BACKGROUND BORDER ---
    # Outer border
    pdf.set_draw_color(0, 177, 64)  # Green
    pdf.set_line_width(3)
    pdf.rect(5, 5, 287, 200)
    
    # Inner border
    pdf.set_draw_color(0, 210, 190)  # Cyan
    pdf.set_line_width(1)
    pdf.rect(10, 10, 277, 190)
    
    # --- HEADER ---
    # Logo
    logo_path = os.path.join("images", "Prysmian logo positive transparent bckgr.png")
    if os.path.exists(logo_path):
        pdf.image(logo_path, 115, 15, 70)
    
    # Certificate title
    pdf.set_y(50)
    pdf.set_font('Helvetica', 'B', 36)
    pdf.set_text_color(28, 36, 52)  # Dark blue
    pdf.cell(0, 15, 'CERTIFICATE', align='C', ln=True)
    
    pdf.set_font('Helvetica', '', 16)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, 'OF COMPLETION', align='C', ln=True)
    
    # --- DIVIDER ---
    pdf.ln(5)
    pdf.set_draw_color(0, 177, 64)
    pdf.set_line_width(0.5)
    pdf.line(80, pdf.get_y(), 217, pdf.get_y())
    pdf.ln(8)
    
    # --- RECIPIENT ---
    pdf.set_font('Helvetica', '', 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, 'This is to certify that', align='C', ln=True)
    
    pdf.set_font('Helvetica', 'B', 28)
    pdf.set_text_color(0, 177, 64)  # Green
    pdf.cell(0, 15, user_name, align='C', ln=True)
    
    pdf.set_font('Helvetica', '', 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, 'has successfully completed the', align='C', ln=True)
    
    pdf.set_font('Helvetica', 'B', 18)
    pdf.set_text_color(28, 36, 52)
    pdf.cell(0, 12, 'IT Induction Program', align='C', ln=True)
    
    # --- COMPLETED GUIDES ---
    pdf.ln(3)
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(80, 80, 80)
    
    # List guides in a single line
    guides_text = " - ".join([sanitize_text(g[:20]) for g in completed_guides[:5]])
    if len(completed_guides) > 5:
        guides_text += f" (+{len(completed_guides) - 5} more)"
    pdf.cell(0, 6, f"Completed: {guides_text}", align='C', ln=True)
    
    # --- DATE ---
    pdf.ln(10)
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(100, 100, 100)
    completion_date = datetime.datetime.now().strftime("%B %d, %Y")
    pdf.cell(0, 8, f'Date of Completion: {completion_date}', align='C', ln=True)
    
    # --- SIGNATURES ---
    pdf.set_y(170)
    
    # Left signature
    pdf.set_x(40)
    pdf.set_draw_color(150, 150, 150)
    pdf.line(40, 175, 120, 175)
    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(100, 100, 100)
    pdf.set_x(40)
    pdf.cell(80, 6, 'IT Department', align='C')
    
    # Right signature
    pdf.set_x(177)
    pdf.line(177, 175, 257, 175)
    pdf.set_x(177)
    pdf.cell(80, 6, 'HR Department', align='C')
    
    # --- FOOTER ---
    pdf.set_y(190)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, 'This certificate was automatically generated by the Prysmian Induction Portal', align='C', ln=True)
    pdf.cell(0, 4, f'Certificate ID: CERT-{datetime.datetime.now().strftime("%Y%m%d")}-{hash(user_email) % 10000:04d}', align='C')
    
    # --- OUTPUT ---
    # Create safe filename
    safe_name = "".join(c for c in user_name if c.isalnum() or c in (' ', '-', '_')).rstrip()
    output_path = os.path.join("documents", f"certificate_{safe_name}.pdf")
    
    try:
        pdf.output(output_path)
        return output_path
    except Exception as e:
        print(f"Error generating certificate: {e}")
        return None


def can_get_certificate():
    """Check if current user can generate a certificate."""
    profile = get_user_profile()
    if not profile:
        return False, "Please register your profile first."
    
    status = get_user_completion_status()
    if not status.get("all_complete"):
        incomplete = [c["name"] for c in status.get("categories", []) if not c["guide_complete"]]
        return False, f"Complete all guides first. Remaining: {len(incomplete)}"
    
    return True, "Ready to generate certificate!"
